# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: 'Angular PR Build'
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    cd AngularApp
    npm install -g @angular/cli@8.0.2
    npm install
    npm run build
  displayName: 'npm install and build'

  # This task runs the tests specified by jest.config.js, including our example accessibility tests.
  #
  # If your project already uses npm instead of yarn, or if your project already runs "jest" directly here,
  # those are both fine.
  #
  # The 2>&1 is a workaround for facebook/jest#5064
  - script: npm run test -- --ci 2>&1 # or "npm run test -- --ci 2>&1"
    displayName: npm test
    workingDirectory: $(Build.SourcesDirectory)/AngularApp

    # This task is how the "Tests" tab in our Azure Pipelines build results page gets its data
  - task: PublishTestResults@2
    displayName: publish test results
    inputs:
      testResultsFiles: $(Build.SourcesDirectory)/AngularApp/test-results/junit.xml
      testRunTitle: AngularApp ($(imageName) $(browser))
    condition: succeededOrFailed()
